spring:
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    #url#spring.datasource.url=jdbc:h2:~/test:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  devtools:
    remote:
      debug:
        enabled: true

logging:
  file: data/logger.log
  level:
    org:
      springframework:
        web: debug
      hibernate: ERROR